version: '3.8'

services:
  database:
    image: "postgres:9.6"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env

  nginx-proxy:
    image: jwilder/nginx-proxy:1.2-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    restart: always
    depends_on:
      - app

volumes:
  dbdata:
